# Generated by Django 3.1.7 on 2021-03-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20210321_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField(verbose_name='')),
            ],
            options={
                'db_table': 'entidad',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='entidad_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='erp.entidad'),
            preserve_default=False,
        ),
    ]
