# Generated by Django 3.1.7 on 2021-03-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20210321_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='entidad_id',
            new_name='entidad',
        ),
    ]
