# Generated by Django 3.1.7 on 2021-03-21 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20210321_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='entidades',
            new_name='entidad',
        ),
    ]
