# Generated by Django 3.1.7 on 2021-03-21 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('CI', models.IntegerField(max_length=10, unique=True)),
                ('nacimiento', models.DateField(default=datetime.datetime.now)),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('direccion', models.TextField(verbose_name='Direccion')),
            ],
            options={
                'db_table': 'persona',
            },
        ),
    ]
