# Generated by Django 3.1.7 on 2021-03-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20210321_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='CI',
            field=models.IntegerField(unique=True),
        ),
    ]
