# Generated by Django 3.1.7 on 2021-03-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20210321_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='entidad',
            new_name='entidades',
        ),
    ]
